@baseUri=http://localhost:3000/api

### test
POST {{baseUri}}/test

###
GET {{baseUri}}/hello-world

### generate wallpaper
POST {{baseUri}}/gen-wallpaper
Content-Type: application/json

{
    "description": "happy new year 2024"
}

### get wallpaper
GET {{baseUri}}/get-wallpapers




### 
POST http://127.0.0.1:5000/chat
Content-Type: application/json

{
    "prompt": "hello world"
}